

import java.util.concurrent.Callable;

public class StatementGenerator implements Callable<String> {

    private BankAccount account;

    public StatementGenerator(BankAccount account) {
        this.account = account;
    }

    @Override
    public String call() throws Exception {

        String threadName = Thread.currentThread().getName();

        System.out.println(
                threadName +
                        " generating statement for Account : "
                        + account.getAccountNumber());

        double closingBalance = account.getOpeningBalance();

        StringBuilder statement = new StringBuilder();

        statement.append("\n==============================\n");
        statement.append("MONTHLY BANK STATEMENT\n");
        statement.append("==============================\n");
        statement.append("Account No : ")
                .append(account.getAccountNumber())
                .append("\n");

        statement.append("Customer   : ")
                .append(account.getCustomerName())
                .append("\n");

        statement.append("Opening Balance : ")
                .append(account.getOpeningBalance())
                .append("\n\n");

        statement.append("Transactions:\n");

        for (Transaction transaction : account.getTransactions()) {

            statement.append(transaction.getTransactionId())
                    .append(" | ")
                    .append(transaction.getTransactionType())
                    .append(" | ")
                    .append(transaction.getAmount())
                    .append("\n");

            if (transaction.getTransactionType()
                    .equalsIgnoreCase("DEPOSIT")) {

                closingBalance += transaction.getAmount();
            }
            else {

                closingBalance -= transaction.getAmount();
            }
        }

        Thread.sleep(2000);

        statement.append("\nClosing Balance : ")
                .append(closingBalance)
                .append("\n");

        statement.append("Generated By : ")
                .append(threadName)
                .append("\n");

        return statement.toString();
    }
}